ImageRuntimeVersion: v4.0.30319
Assembly ztacadmgd, Version=1.0.*, Culture=固定语言(固定国家/地区): 
	hash=SHA1, flags=PublicKey
Assembly mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089: 
	hash=None, flags=None
Assembly System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089: 
	hash=None, flags=None
Assembly System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089: 
	hash=None, flags=None
Assembly System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089: 
	hash=None, flags=None
Assembly System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089: 
	hash=None, flags=None
Assembly Acdbmgd, Version=19.0.*, Culture=固定语言(固定国家/地区): 
	hash=None, flags=None
Assembly Acmgd, Version=19.0.*, Culture=固定语言(固定国家/地区): 
	hash=None, flags=None
Assembly AcCui, Version=19.0.*, Culture=固定语言(固定国家/地区): 
	hash=None, flags=None
Assembly Microsoft.VisualC, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: 
	hash=None, flags=None
Class ztAcadMgd.DatabaseServices.Curve: AutoLayout, AnsiClass, Class, Public, BeforeFieldInit
  :Autodesk.AutoCAD.DatabaseServices.Entity
  Properties:
    Autodesk.AutoCAD.Geometry.Point3d StartPoint 'get set' : 
    Double StartParam 'get ' : 
    Boolean IsPeriodic 'get ' : 
    Autodesk.AutoCAD.Geometry.Point3d EndPoint 'get set' : 
    Double EndParam 'get ' : 
    Boolean Closed 'get ' : 
    Double Area 'get ' : 
  Methods:
    GetDistanceAtParameter(Double): PrivateScope, Public, HideBySig
    GetDistAtPoint(Point3d): PrivateScope, Public, HideBySig
    GetFirstDerivative(Double): PrivateScope, Public, HideBySig
    GetFirstDerivative(Point3d): PrivateScope, Public, HideBySig
    GetParameterAtDistance(Double): PrivateScope, Public, HideBySig
    GetParameterAtPoint(Point3d): PrivateScope, Public, HideBySig
    GetPointAtDist(Double): PrivateScope, Public, HideBySig
    GetPointAtParameter(Double): PrivateScope, Public, HideBySig
    GetSecondDerivative(Double): PrivateScope, Public, HideBySig
    get_Area(): PrivateScope, Public, HideBySig, SpecialName
    get_Closed(): PrivateScope, Public, HideBySig, SpecialName
    get_EndParam(): PrivateScope, Public, HideBySig, SpecialName
    get_EndPoint(): PrivateScope, Public, Virtual, HideBySig, VtableLayoutMask, SpecialName
    set_EndPoint(Point3d): PrivateScope, Public, Virtual, HideBySig, VtableLayoutMask, SpecialName
    get_IsPeriodic(): PrivateScope, Public, HideBySig, SpecialName
    get_StartParam(): PrivateScope, Public, HideBySig, SpecialName
    get_StartPoint(): PrivateScope, Public, Virtual, HideBySig, VtableLayoutMask, SpecialName
    set_StartPoint(Point3d): PrivateScope, Public, Virtual, HideBySig, VtableLayoutMask, SpecialName
Class ztAcadMgd.DatabaseServices.Arc: AutoLayout, AnsiClass, Class, Public, BeforeFieldInit
  :ztAcadMgd.DatabaseServices.Curve
    Void .ctor(Autodesk.AutoCAD.Geometry.Point3d, Autodesk.AutoCAD.Geometry.Vector3d, Double, Double, Double): PrivateScope, Public, HideBySig, SpecialName, RTSpecialName
    Void .ctor(Autodesk.AutoCAD.Geometry.Point3d, Double, Double, Double): PrivateScope, Public, HideBySig, SpecialName, RTSpecialName
    Void .ctor(): PrivateScope, Public, HideBySig, SpecialName, RTSpecialName
  Properties:
    Double TotalAngle 'get ' : 
    Double Thickness 'get set' : 
    Double StartAngle 'get set' : 
    Double Radius 'get set' : 
    Autodesk.AutoCAD.Geometry.Vector3d Normal 'get set' : 
    Double Length 'get ' : 
    Double EndAngle 'get set' : 
    Autodesk.AutoCAD.Geometry.Point3d Center 'get set' : 
  Methods:
    get_Center(): PrivateScope, Public, HideBySig, SpecialName
    set_Center(Point3d): PrivateScope, Public, HideBySig, SpecialName
    get_EndAngle(): PrivateScope, Public, HideBySig, SpecialName
    set_EndAngle(Double): PrivateScope, Public, HideBySig, SpecialName
    get_Length(): PrivateScope, Public, HideBySig, SpecialName
    get_Normal(): PrivateScope, Public, HideBySig, SpecialName
    set_Normal(Vector3d): PrivateScope, Public, HideBySig, SpecialName
    get_Radius(): PrivateScope, Public, HideBySig, SpecialName
    set_Radius(Double): PrivateScope, Public, HideBySig, SpecialName
    get_StartAngle(): PrivateScope, Public, HideBySig, SpecialName
    set_StartAngle(Double): PrivateScope, Public, HideBySig, SpecialName
    get_Thickness(): PrivateScope, Public, HideBySig, SpecialName
    set_Thickness(Double): PrivateScope, Public, HideBySig, SpecialName
    get_TotalAngle(): PrivateScope, Public, HideBySig, SpecialName
Class ztAcadMgd.DatabaseServices.BlockReference: AutoLayout, AnsiClass, Class, Public, BeforeFieldInit
  :Autodesk.AutoCAD.DatabaseServices.Entity
    Void .ctor(Autodesk.AutoCAD.Geometry.Point3d, System.ValueType): PrivateScope, Public, HideBySig, SpecialName, RTSpecialName
    Void .ctor(): PrivateScope, Public, HideBySig, SpecialName, RTSpecialName
  Properties:
    Double Rotation 'get set' : 
    Autodesk.AutoCAD.Geometry.Point3d Position 'get set' : 
    Autodesk.AutoCAD.Geometry.Vector3d Normal 'get set' : 
  Methods:
    get_Normal(): PrivateScope, Public, HideBySig, SpecialName
    set_Normal(Vector3d): PrivateScope, Public, HideBySig, SpecialName
    get_Position(): PrivateScope, Public, Virtual, HideBySig, SpecialName
    set_Position(Point3d): PrivateScope, Public, Virtual, HideBySig, SpecialName
    get_Rotation(): PrivateScope, Public, HideBySig, SpecialName
    set_Rotation(Double): PrivateScope, Public, HideBySig, SpecialName
Class ztAcadMgd.DatabaseServices.Circle: AutoLayout, AnsiClass, Class, Public, BeforeFieldInit
  :ztAcadMgd.DatabaseServices.Curve
    Void .ctor(Autodesk.AutoCAD.Geometry.Point3d, Autodesk.AutoCAD.Geometry.Vector3d, Double): PrivateScope, Public, HideBySig, SpecialName, RTSpecialName
    Void .ctor(): PrivateScope, Public, HideBySig, SpecialName, RTSpecialName
  Properties:
    Double Thickness 'get set' : 
    Double Radius 'get set' : 
    Autodesk.AutoCAD.Geometry.Vector3d Normal 'get set' : 
    Autodesk.AutoCAD.Geometry.Point3d Center 'get set' : 
  Methods:
    get_Center(): PrivateScope, Public, HideBySig, SpecialName
    set_Center(Point3d): PrivateScope, Public, HideBySig, SpecialName
    get_Normal(): PrivateScope, Public, HideBySig, SpecialName
    set_Normal(Vector3d): PrivateScope, Public, HideBySig, SpecialName
    get_Radius(): PrivateScope, Public, HideBySig, SpecialName
    set_Radius(Double): PrivateScope, Public, HideBySig, SpecialName
    get_Thickness(): PrivateScope, Public, HideBySig, SpecialName
    set_Thickness(Double): PrivateScope, Public, HideBySig, SpecialName
Class ztAcadMgd.DatabaseServices.DBText: AutoLayout, AnsiClass, Class, Public, BeforeFieldInit
  :Autodesk.AutoCAD.DatabaseServices.Entity
    Void .ctor(): PrivateScope, Public, HideBySig, SpecialName, RTSpecialName
  Properties:
    Double WidthFactor 'get set' : 
    Double Thickness 'get set' : 
    System.ValueType TextStyle 'get set' ObjectId IsBoxed : 
    System.String TextString 'get set' : 
    Double Rotation 'get set' : 
    Autodesk.AutoCAD.Geometry.Point3d Position 'get set' : 
    Double Oblique 'get set' : 
    Autodesk.AutoCAD.Geometry.Vector3d Normal 'get set' : 
    Double Height 'get set' : 
    Autodesk.AutoCAD.Geometry.Point3d AlignmentPoint 'get set' : 
  Methods:
    get_AlignmentPoint(): PrivateScope, Public, HideBySig, SpecialName
    set_AlignmentPoint(Point3d): PrivateScope, Public, HideBySig, SpecialName
    get_Height(): PrivateScope, Public, HideBySig, SpecialName
    set_Height(Double): PrivateScope, Public, HideBySig, SpecialName
    get_Normal(): PrivateScope, Public, HideBySig, SpecialName
    set_Normal(Vector3d): PrivateScope, Public, HideBySig, SpecialName
    get_Oblique(): PrivateScope, Public, HideBySig, SpecialName
    set_Oblique(Double): PrivateScope, Public, HideBySig, SpecialName
    get_Position(): PrivateScope, Public, HideBySig, SpecialName
    set_Position(Point3d): PrivateScope, Public, HideBySig, SpecialName
    get_Rotation(): PrivateScope, Public, HideBySig, SpecialName
    set_Rotation(Double): PrivateScope, Public, HideBySig, SpecialName
    get_TextString(): PrivateScope, Public, HideBySig, SpecialName
    set_TextString(String): PrivateScope, Public, HideBySig, SpecialName
    get_TextStyle(): PrivateScope, Public, HideBySig, SpecialName
    set_TextStyle(ValueType ObjectId IsBoxed): PrivateScope, Public, HideBySig, SpecialName
    get_Thickness(): PrivateScope, Public, HideBySig, SpecialName
    set_Thickness(Double): PrivateScope, Public, HideBySig, SpecialName
    get_WidthFactor(): PrivateScope, Public, HideBySig, SpecialName
    set_WidthFactor(Double): PrivateScope, Public, HideBySig, SpecialName
Class ztAcadMgd.DatabaseServices.Line: AutoLayout, AnsiClass, Class, Public, BeforeFieldInit
  :ztAcadMgd.DatabaseServices.Curve
    Void .ctor(Autodesk.AutoCAD.Geometry.Point3d, Autodesk.AutoCAD.Geometry.Point3d): PrivateScope, Public, HideBySig, SpecialName, RTSpecialName
    Void .ctor(): PrivateScope, Public, HideBySig, SpecialName, RTSpecialName
  Properties:
    Autodesk.AutoCAD.Geometry.Point3d StartPoint 'get set' : 
    Autodesk.AutoCAD.Geometry.Point3d EndPoint 'get set' : 
  Methods:
    get_EndPoint(): PrivateScope, Public, Virtual, HideBySig, SpecialName
    set_EndPoint(Point3d): PrivateScope, Public, Virtual, HideBySig, SpecialName
    get_StartPoint(): PrivateScope, Public, Virtual, HideBySig, SpecialName
    set_StartPoint(Point3d): PrivateScope, Public, Virtual, HideBySig, SpecialName
    GetValue(String): PrivateScope, Public, HideBySig
    SetValue(String, String): PrivateScope, Public, HideBySig
    AddPersistentReactor(ObjectId): PrivateScope, Public, HideBySig
    RemovePersistentReactor(ObjectId): PrivateScope, Public, HideBySig
Class ztAcadMgd.DatabaseServices.MText: AutoLayout, AnsiClass, Class, Public, BeforeFieldInit
  :Autodesk.AutoCAD.DatabaseServices.Entity
    Void .ctor(): PrivateScope, Public, HideBySig, SpecialName, RTSpecialName
  Properties:
    Double Width 'get set' : 
    System.ValueType TextStyle 'get set' ObjectId IsBoxed : 
    Double TextHeight 'get set' : 
    Double Rotation 'get set' : 
    Autodesk.AutoCAD.Geometry.Vector3d Normal 'get set' : 
    Autodesk.AutoCAD.Geometry.Point3d Location 'get set' : 
    System.String Contents 'get set' : 
    System.String ColorChange 'get ' : 
    System.String BlockEnd 'get ' : 
    Double Ascent 'get ' : 
    System.String AlignChange 'get ' : 
    Double ActualWidth 'get ' : 
    Double ActualHeight 'get ' : 
  Methods:
    get_ActualHeight(): PrivateScope, Public, HideBySig, SpecialName
    get_ActualWidth(): PrivateScope, Public, HideBySig, SpecialName
    get_AlignChange(): PrivateScope, Public, Static, HideBySig, SpecialName
    get_Ascent(): PrivateScope, Public, HideBySig, SpecialName
    get_BlockEnd(): PrivateScope, Public, Static, HideBySig, SpecialName
    get_ColorChange(): PrivateScope, Public, Static, HideBySig, SpecialName
    get_Contents(): PrivateScope, Public, HideBySig, SpecialName
    set_Contents(String): PrivateScope, Public, HideBySig, SpecialName
    get_Location(): PrivateScope, Public, HideBySig, SpecialName
    set_Location(Point3d): PrivateScope, Public, HideBySig, SpecialName
    get_Normal(): PrivateScope, Public, HideBySig, SpecialName
    set_Normal(Vector3d): PrivateScope, Public, HideBySig, SpecialName
    get_Rotation(): PrivateScope, Public, HideBySig, SpecialName
    set_Rotation(Double): PrivateScope, Public, HideBySig, SpecialName
    get_TextHeight(): PrivateScope, Public, HideBySig, SpecialName
    set_TextHeight(Double): PrivateScope, Public, HideBySig, SpecialName
    get_TextStyle(): PrivateScope, Public, HideBySig, SpecialName
    set_TextStyle(ValueType ObjectId IsBoxed): PrivateScope, Public, HideBySig, SpecialName
    get_Width(): PrivateScope, Public, HideBySig, SpecialName
    set_Width(Double): PrivateScope, Public, HideBySig, SpecialName
Class ztAcadMgd.DatabaseServices.Polyline: AutoLayout, AnsiClass, Class, Public, BeforeFieldInit
  :ztAcadMgd.DatabaseServices.Curve
    Void .ctor(Int32): PrivateScope, Public, HideBySig, SpecialName, RTSpecialName
    Void .ctor(): PrivateScope, Public, HideBySig, SpecialName, RTSpecialName
Class ztAcadMgd.DatabaseServices.Group: AutoLayout, AnsiClass, Class, Public, BeforeFieldInit
  :Autodesk.AutoCAD.DatabaseServices.DBObject
    Void .ctor(): PrivateScope, Public, HideBySig, SpecialName, RTSpecialName
  Properties:
    System.String Name 'get set' : 
  Methods:
    get_Name(): PrivateScope, Public, HideBySig, SpecialName
    set_Name(String): PrivateScope, Public, HideBySig, SpecialName
